# Generated by Django 5.0.6 on 2024-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_breast_created_at_breast_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
